from typing import Any, Optional

class ChunkedBytesIO:
    contents: Any = ...
    pos: Any = ...
    def __init__(self, contents: Any) -> None: ...
    def read(self, maxbytes: Optional[Any] = ...): ...

def tar_stream(store: Any, tree: Any, mtime: Any, prefix: bytes = ..., format: str = ...) -> None: ...
