from dulwich.config import ConfigDict, get_xdg_config_home_path as get_xdg_config_home_path
from dulwich.errors import GitProtocolError as GitProtocolError, NotGitRepository as NotGitRepository, SendPackError as SendPackError
from dulwich.pack import write_pack_data as write_pack_data, write_pack_objects as write_pack_objects
from dulwich.protocol import CAPABILITIES_REF as CAPABILITIES_REF, CAPABILITY_AGENT as CAPABILITY_AGENT, CAPABILITY_DELETE_REFS as CAPABILITY_DELETE_REFS, CAPABILITY_INCLUDE_TAG as CAPABILITY_INCLUDE_TAG, CAPABILITY_MULTI_ACK as CAPABILITY_MULTI_ACK, CAPABILITY_MULTI_ACK_DETAILED as CAPABILITY_MULTI_ACK_DETAILED, CAPABILITY_OFS_DELTA as CAPABILITY_OFS_DELTA, CAPABILITY_QUIET as CAPABILITY_QUIET, CAPABILITY_REPORT_STATUS as CAPABILITY_REPORT_STATUS, CAPABILITY_SHALLOW as CAPABILITY_SHALLOW, CAPABILITY_SIDE_BAND_64K as CAPABILITY_SIDE_BAND_64K, CAPABILITY_SYMREF as CAPABILITY_SYMREF, CAPABILITY_THIN_PACK as CAPABILITY_THIN_PACK, COMMAND_DEEPEN as COMMAND_DEEPEN, COMMAND_DONE as COMMAND_DONE, COMMAND_HAVE as COMMAND_HAVE, COMMAND_SHALLOW as COMMAND_SHALLOW, COMMAND_UNSHALLOW as COMMAND_UNSHALLOW, COMMAND_WANT as COMMAND_WANT, HangupException as HangupException, KNOWN_RECEIVE_CAPABILITIES as KNOWN_RECEIVE_CAPABILITIES, KNOWN_UPLOAD_CAPABILITIES as KNOWN_UPLOAD_CAPABILITIES, PktLineParser as PktLineParser, Protocol as Protocol, ProtocolFile as ProtocolFile, SIDE_BAND_CHANNEL_DATA as SIDE_BAND_CHANNEL_DATA, SIDE_BAND_CHANNEL_FATAL as SIDE_BAND_CHANNEL_FATAL, SIDE_BAND_CHANNEL_PROGRESS as SIDE_BAND_CHANNEL_PROGRESS, TCP_GIT_PORT as TCP_GIT_PORT, ZERO_SHA as ZERO_SHA, agent_string as agent_string, capability_agent as capability_agent, extract_capabilities as extract_capabilities, extract_capability_names as extract_capability_names, parse_capability as parse_capability
from dulwich.refs import ANNOTATED_TAG_SUFFIX as ANNOTATED_TAG_SUFFIX, read_info_refs as read_info_refs
from typing import Any, Dict, Iterable, List, Optional, Tuple, Union
import dulwich.contrib.paramiko_vendor

class InvalidWants(Exception):
    def __init__(self, wants: Any) -> None: ...

class HTTPUnauthorized(Exception):
    www_authenticate: Any = ...
    def __init__(self, www_authenticate: Any) -> None: ...

COMMON_CAPABILITIES: List[bytes]
UPLOAD_CAPABILITIES: List[bytes]
RECEIVE_CAPABILITIES: List[bytes]

class ReportStatusParser:
    def __init__(self) -> None: ...
    def check(self) -> SendPackError: ...
    def handle_packet(self, pkt: Any) -> None: ...

def read_pkt_refs(proto: Any): ...

class FetchPackResult:
    refs: Any = ...
    symrefs: Any = ...
    agent: Any = ...
    new_shallow: Any = ...
    new_unshallow: Any = ...
    def __init__(self, refs: Any, symrefs: Any, agent: Any, new_shallow: Optional[Any] = ..., new_unshallow: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __contains__(self, name: Any): ...
    def __getitem__(self, name: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __getattribute__(self, name: Any): ...

class SendPackResult:
    refs: Any = ...
    agent: Any = ...
    ref_status: Any = ...
    def __init__(self, refs: Any, agent: Optional[Any] = ..., ref_status: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __contains__(self, name: Any): ...
    def __getitem__(self, name: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __getattribute__(self, name: Any): ...

class GitClient:
    def __init__(self, thin_packs: bool = ..., report_activity: Optional[Any] = ..., quiet: bool = ..., include_tags: bool = ...) -> None: ...
    def get_url(self, path: Any) -> str: ...
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any) -> GitClient: ...
    def send_pack(self, path: Any, update_refs: Any, generate_pack_data: Any, progress: Optional[Any] = ...) -> SendPackResult: ...
    def fetch(self, path: Any, target: Any, determine_wants: Optional[Any] = ..., progress: Optional[Any] = ..., depth: Optional[Any] = ...): ...
    def fetch_pack(self, path: Any, determine_wants: Any, graph_walker: Any, pack_data: Any, progress: Optional[Any] = ..., depth: Optional[Any] = ...) -> FetchPackResult: ...
    def get_refs(self, path: bytes) -> None: ...

def check_wants(wants: Any, refs: Any) -> None: ...

class TraditionalGitClient(GitClient):
    DEFAULT_ENCODING: str = ...
    def __init__(self, path_encoding: Any = ..., **kwargs: Any) -> None: ...
    def send_pack(self, path: Any, update_refs: Any, generate_pack_data: Any, progress: Optional[Any] = ...) -> SendPackResult: ...
    def fetch_pack(self, path: Any, determine_wants: Any, graph_walker: Any, pack_data: Any, progress: Optional[Any] = ..., depth: Optional[Any] = ...) -> FetchPackResult: ...
    def get_refs(self, path: Any): ...
    def archive(self, path: Any, committish: Any, write_data: Any, progress: Optional[Any] = ..., write_error: Optional[Any] = ..., format: Optional[Any] = ..., subdirs: Optional[Any] = ..., prefix: Optional[Any] = ...) -> None: ...

class TCPGitClient(TraditionalGitClient):
    def __init__(self, host: Any, port: Optional[Any] = ..., **kwargs: Any) -> None: ...
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any): ...
    def get_url(self, path: Any): ...

class SubprocessWrapper:
    proc: Any = ...
    read: Any = ...
    write: Any = ...
    def __init__(self, proc: Any) -> None: ...
    @property
    def stderr(self): ...
    def can_read(self): ...
    def close(self) -> None: ...

def find_git_command(): ...

class SubprocessGitClient(TraditionalGitClient):
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any): ...
    git_command: Any = ...

class LocalGitClient(GitClient):
    def __init__(self, thin_packs: bool = ..., report_activity: Optional[Any] = ..., config: Optional[Any] = ...) -> None: ...
    def get_url(self, path: Any): ...
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any): ...
    def send_pack(self, path: Any, update_refs: Any, generate_pack_data: Any, progress: Optional[Any] = ...) -> SendPackResult: ...
    def fetch(self, path: Any, target: Any, determine_wants: Optional[Any] = ..., progress: Optional[Any] = ..., depth: Optional[Any] = ...): ...
    def fetch_pack(self, path: Any, determine_wants: Any, graph_walker: Any, pack_data: Any, progress: Optional[Any] = ..., depth: Optional[Any] = ...) -> FetchPackResult: ...
    def get_refs(self, path: Any): ...
default_local_git_client_cls = LocalGitClient

class SSHVendor:
    def connect_ssh(self, host: Any, command: Any, username: Optional[Any] = ..., port: Optional[Any] = ..., password: Optional[Any] = ..., key_filename: Optional[Any] = ...): ...
    def run_command(self, host: Any, command: Any, username: Optional[Any] = ..., port: Optional[Any] = ..., password: Optional[Any] = ..., key_filename: Optional[Any] = ...) -> None: ...

class StrangeHostname(Exception):
    def __init__(self, hostname: Any) -> None: ...

class SubprocessSSHVendor(SSHVendor):
    def run_command(self, host: Any, command: Any, username: Optional[Any] = ..., port: Optional[Any] = ..., password: Optional[Any] = ..., key_filename: Optional[Any] = ...): ...

class PLinkSSHVendor(SSHVendor):
    def run_command(self, host: Any, command: Any, username: Optional[Any] = ..., port: Optional[Any] = ..., password: Optional[Any] = ..., key_filename: Optional[Any] = ...): ...

def ParamikoSSHVendor(**kwargs: Any) -> dulwich.contrib.paramiko_vendor.ParamikoSSHVendor: ...

get_ssh_vendor = SubprocessSSHVendor

class SSHGitClient(TraditionalGitClient):
    host: Any = ...
    port: Any = ...
    username: Any = ...
    password: Any = ...
    key_filename: Any = ...
    alternative_paths: Any = ...
    ssh_vendor: Any = ...
    def __init__(self, host: Any, port: Optional[Any] = ..., username: Optional[Any] = ..., vendor: Optional[Any] = ..., config: Optional[Any] = ..., password: Optional[Any] = ..., key_filename: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def get_url(self, path: Any): ...
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any): ...

def default_user_agent_string() -> str: ...
def default_urllib3_manager(config: ConfigDict, pool_manager_cls: Optional[Any] = ..., proxy_manager_cls: Optional[Any] = ..., **override_kwargs: Any): ...

class HttpGitClient(GitClient):
    dumb: Any = ...
    pool_manager: Any = ...
    def __init__(self, base_url: Any, dumb: Optional[Any] = ..., pool_manager: Optional[Any] = ..., config: Optional[Any] = ..., username: Optional[Any] = ..., password: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def get_url(self, path: Any): ...
    @classmethod
    def from_parsedurl(cls, parsedurl: Any, **kwargs: Any): ...
    def send_pack(self, path: bytes, update_refs: Any, generate_pack_data: Any, progress: Optional[Any] = ...) -> SendPackResult: ...
    def fetch_pack(self, path: Any, determine_wants: Any, graph_walker: Any, pack_data: Any, progress: Optional[Any] = ..., depth: Optional[Any] = ...) -> FetchPackResult: ...
    def get_refs(self, path: Any): ...

def get_transport_and_path_from_url(url: Any, config: Optional[Any] = ..., *, thin_packs: Any = ..., report_activity: Any = ...) -> Tuple[GitClient, Any]: ...
def parse_rsync_url(location: str) -> Tuple[Any, Any, Any]: ...
def get_transport_and_path(location: Any, *, config: Any = ..., thin_packs: Any = ..., report_activity: Any = ...) -> Tuple[GitClient, Any]: ...

DEFAULT_GIT_CREDENTIALS_PATHS: List[str]

def get_credentials_from_store(scheme: Any, hostname: Any, username: Optional[Any] = ..., fnames: Iterable[Union[str, bytes]] = ...): ...
