from typing import Any

def ensure_dir_exists(dirname: Any) -> None: ...
def GitFile(filename: Any, mode: str = ..., bufsize: int = ...): ...

class FileLocked(Exception):
    filename: Any = ...
    lockfilename: Any = ...
    def __init__(self, filename: Any, lockfilename: Any) -> None: ...

class _GitFile:
    PROXY_PROPERTIES: Any = ...
    PROXY_METHODS: Any = ...
    def __init__(self, filename: Any, mode: Any, bufsize: Any) -> None: ...
    def abort(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getattr__(self, name: Any): ...
