from typing import Any

class LFSStore:
    path: Any = ...
    def __init__(self, path: Any) -> None: ...
    @classmethod
    def create(cls, lfs_dir: Any): ...
    @classmethod
    def from_repo(cls, repo: Any, create: bool = ...): ...
    def open_object(self, sha: Any): ...
    def write_object(self, chunks: Any): ...
