from typing import Any, Optional

def parse_identity(text: Any): ...
def read_mailmap(f: Any) -> None: ...

class Mailmap:
    def __init__(self, map: Optional[Any] = ...) -> None: ...
    def add_entry(self, canonical_identity: Any, from_identity: Optional[Any] = ...) -> None: ...
    def lookup(self, identity: Any): ...
    @classmethod
    def from_path(cls, path: Any): ...
