from typing import Any

def to_bytes(text: Any): ...
def parse_object(repo: Any, objectish: Any): ...
def parse_tree(repo: Any, treeish: Any): ...
def parse_ref(container: Any, refspec: Any): ...
def parse_reftuple(lh_container: Any, rh_container: Any, refspec: Any, force: bool = ...): ...
def parse_reftuples(lh_container: Any, rh_container: Any, refspecs: Any, force: bool = ...): ...
def parse_refs(container: Any, refspecs: Any): ...
def parse_commit_range(repo: Any, committishs: Any): ...

class AmbiguousShortId(Exception):
    prefix: Any = ...
    options: Any = ...
    def __init__(self, prefix: Any, options: Any) -> None: ...

def scan_for_short_id(object_store: Any, prefix: Any): ...
def parse_commit(repo: Any, committish: Any): ...
