import unittest
from dulwich.contrib import release_robot as release_robot
from dulwich.repo import Repo as Repo
from dulwich.tests.utils import make_commit as make_commit, make_tag as make_tag
from typing import Any

BASEDIR: Any

def gmtime_to_datetime(gmt: Any): ...

class TagPatternTests(unittest.TestCase):
    def test_tag_pattern(self) -> None: ...

class GetRecentTagsTest(unittest.TestCase):
    test_repo: Any = ...
    committer: bytes = ...
    test_tags: Any = ...
    tag_test_data: Any = ...
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    def test_get_recent_tags(self) -> None: ...
